runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: src.main.app

- url: /
  static_files: assets/index.html
  upload: assets/index.html

- url: .*
  static_dir: assets

libraries:
- name: pycrypto
  version: latest
