runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/task/.*
  script: src.main.app
  login: admin

- url: /api/.*
  script: src.main.app

- url: /signin/.*
  script: src.main.app

- url: /auth/.*
  script: src.main.app

- url: /invitation/.*
  script: src.main.app

- url: /
  static_files: assets/index.html
  upload: assets/index.html

- url: .*
  static_dir: assets

libraries:
- name: pycrypto
  version: latest

- name: ssl
  version: latest

env_variables:
  OAUTHLIB_INSECURE_TRANSPORT: True
