application: gae-pomodoro
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: src.main.app

libraries:
- name: pycrypto
  version: latest
